allowBuilds:
  puppeteer: true
  unrs-resolver: true
catalog:
  vite: https://pkg.pr.new/voidzero-dev/vite-plus/@voidzero-dev/vite-plus-core@1856
  vitest: 4.1.9
  vite-plus: https://pkg.pr.new/voidzero-dev/vite-plus@1856
overrides:
  vite: "catalog:"
  vitest: "catalog:"
  minimatch: ">=3.1.4"
nodeVersion: 22.22.3
blockExoticSubdeps: false
minimumReleaseAge: 60
minimumReleaseAgeExclude:
  - "@voidzero-dev/*"
  - vite-plus
  - "@vitest/*"
  - vite
  - vitest
  - "@oxc-project/*"
  - "@oxlint/*"
  - oxlint
  - oxfmt
  - oxlint-tsgolint
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
